from openai import OpenAI
from dotenv import load_dotenv
import os
import json
import time
from datetime import datetime
from playwright.sync_api import sync_playwright
from assertion_runner import run_real_assertion
from ai_engine import generate_test_cases
from reporting import generate_report, log_validation_results
from test_executor import execute_tests
from ai_validator import validate_test_cases
from test_ai_validator import run_validator_tests
from validation_force_failure import force_failure


DEBUG = False

PLANS_DIR = "test_cases"
os.makedirs(PLANS_DIR, exist_ok=True) # Create the txt test_cases directory if it doesn't exist.

PLANS_DIR_JSON = "test_cases_json"
os.makedirs(PLANS_DIR_JSON, exist_ok=True) # Create the json test_cases_json directory

RESULTS_DIR = "test_results"
os.makedirs(RESULTS_DIR, exist_ok=True) # Create the txt results directory if it doesn't exist

RESULTS_JSON_DIR = "test_results_json"
os.makedirs(RESULTS_JSON_DIR, exist_ok=True) # Create the json results directory if it doesn't exist


load_dotenv()
MODEL = "gpt-4o-mini"


# This function takes a task description as input and generates a safe filename by removing special characters, replacing spaces with underscores, and limiting the length to 50 characters. This is used to create filenames for saving test plans that are descriptive of the task while ensuring they are valid and not too long for most file systems.
def make_safe_filename(task: str) -> str:
    return "".join(
        c for c in task.lower()
        if c.isalnum() or c == " "
    ).strip().replace(" ", "_")[:50]

def run_default_tests():
    files = [file for file in os.listdir(PLANS_DIR_JSON) if file.endswith(".json")]

    if not files: 
        print("No saved test cases found.")
        return
    
    filepath = os.path.join(PLANS_DIR_JSON, files[0]) # Just take the first file for default testing
    test_cases = load_test_cases(filepath)

    results = execute_tests(test_cases)

    generate_report(results) 

# Search for test plan files
def list_plans():
    # files returns a list of all files in the test_plans directory that start with "plan_"
    files = [f for f in os.listdir(PLANS_DIR) if f.startswith("plan_")]
    
    # if not files checks if the list is empty. If it is empty, it prints "No test plans found." and returns an empty list. This is to handle the case where there are no plans saved yet.
    if not files:
        print("No test plans found.")
        return[]
    
    print("\nSaved test plans:")

    # enumerate(files, start=1) gives us both the index (starting from 1) and the filename for each file in the list. We can then print them in a numbered list format.
    for i, file in enumerate(files, start=1):
        print(f"{i}. {file}")
    
    return files


# Read file logic.
def read_plan(filename:str):
    filepath = os.path.join(PLANS_DIR, filename)
    try:
        with open(filepath,"r") as file:
            content=file.read()
            print("\n--- Plan Content ---\n")
            print(content)
    except FileNotFoundError:
        print(f"File {filename} not found.")
    input("\nPress Enter to continue...")

def load_test_cases(filepath:str):
    with open(filepath, "r") as file:
        data = json.load(file)
        return data["test_cases"]

# Sanitizes JSON response, returns cleaned JSON string. Has additional debugging output to help troubleshoot issues with AI responses.
def break_down_task(task: str, feedback: str = "") -> str:
    print("Breaking task down...")

    raw_text = generate_test_cases(task, feedback) # pass feedback into AI generator for iterative improvement

    if DEBUG:
        print("\n--- RAW AI RESPONSE ---\n")
        print(raw_text)
    
    cleaned = raw_text.strip() # Remove leading and trailing whitespace. Whitespace can cause issues when trying to parse JSON

    if cleaned.startswith("```"):
        cleaned = cleaned.replace("```json","").replace("```","").strip() # If the response is wrapped in markdown code blocks, remove them.
    
    if DEBUG:
        print("\n--- CLEANED JSON ---\n")
        print(cleaned)

    return cleaned


# Takes the test cases generated by the AI and executes them using Playwright. For each test case, it prints the steps and expected result, performs the actions on the page, and runs the assertion. If an assertion fails, it catches the AssertionError and prints a failure message instead of stopping the whole test run.



# Main helper function that orchestrates the workflow of the application. It does the following:
# 1. Takes a task description as input
# 2. Calls break_down_task to get test cases from the AI
# 3. Parses the AI response as JSON and extracts the test cases
# 4. Calls run_test_cases to execute the test cases using Playwright
# 5. Saves the test cases to a text file in the test_cases directory with a timestamp and task description in the filename for easy reference
def job_helper(task: str) -> str:
    print("\nGenerating test cases...")

    MAX_RETRIES = 2
    feedback = ""

    for attempt in range(MAX_RETRIES + 1): 
        breakdown = break_down_task(task, feedback)

        try:
            data = json.loads(breakdown)
            test_cases = data.get("test_cases",[])
        except:
            print("JSON parse failed")
            continue

        validation_results = validate_test_cases(test_cases)

        # Print validation results for all test cases
        for result in validation_results:
            print(f"\nAI VALIDATION: {result['title']}")
            print(f"Score: {result['score']}")
            print(f"Confidence: {result['confidence']}")

            if result["issues"]:
                for issue in result["issues"]["critical"]:
                    print(f"[CRITICAL] {issue}")
                for issue in result["issues"]["warning"]:
                    print(f"[WARNING] {issue}")

        if all(result["valid"] for result in validation_results): # If result field is valid, pass the check
            print("\nAI output passed validation\n")
            break
        
        # Send feedback to prompt 
        for result in validation_results:
            if not result["valid"]:
                feedback += f"\nTest Case: {result['title']}\n"
                for issue in result["issues"]["critical"]:
                    feedback += f"- {issue}\n"
        else:
            print(f"\nValidation failed (attempt {attempt + 1})")

            if attempt == MAX_RETRIES:
                print("Max retries reached. Blocking execution.")
                return
    

    log_validation_results(validation_results) # Save validation history
    results = execute_tests(test_cases)
    generate_report(results)

    safe_task = make_safe_filename(task)
    filename = f"plan_{safe_task}.txt"
    filename = os.path.join(PLANS_DIR, f"plan_{safe_task}.txt") # save the file in the test_plans directory

        # opens a file called plan.txt in write mode. If the file doesn't exist, it will be created. If it does exist, it will be overwritten.
        # "w" writes to the file, "a" appends to the file, "r" reads the file. We use a context manager (the with statement) to ensure that the file is properly closed after we're done writing to it.
    with open(filename,"w") as file: 
        file.write(f"\n=== {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} ===\n")
        file.write(f"Generated by AI QA Assistant\n")
        file.write(f"Task: {task}\n")
        file.write(f"\n\n=== Test Cases ===\n")
        for case in test_cases:
            file.write(f"\nTest Case ({case['type']}): {case['title']}\n")
            for i, step in enumerate(case["steps"], start=1):
                file.write(f"{i}. {step}\n")
            file.write(f"Expected: {case['expected']}\n")
            file.write(f"Assertion: {case['assertion']}\n")
    
    safe_task = make_safe_filename(task)
    json_filename = os.path.join(PLANS_DIR_JSON, f"{safe_task}.json") # save the JSON file in the test_cases_json directory with a similar name to the txt file for easy reference

    with open(json_filename,"w") as jf:
        # Wrap test cases because we want to maintain the same structure as the original AI response for easier parsing and integration with other tools in an enterprise application. This also allows us to save any additional metadata or fields that may be added to the test cases in the future without needing to change the saving logic.
        data = {
            "test_cases": test_cases
        }
        json.dump(data, jf, indent=4) # Save the test cases in JSON format for easier parsing and integration with other tools in an enterprise application.
    


    return ""


# Execution
if __name__ == "__main__":
    while True:
        print("\n=== Test Planner ===")
        print("1. Create new plan")
        print("2. View saved plans")
        print("3. Run saved test cases")
        print("4. Exit")

        choice = input("Choose an option: ")

        if choice == "1":
            task = input("Enter a task: ")
            result = job_helper(task)
            print(result)
        
        elif choice == "2":
            files = list_plans()

            # If no files are found, print a message and skip to the next iteration of the loop
            if not files:
                continue

            file_choice = input("\nEnter number to view: ")

            # Check if the input is a numeric digit and within the valid range of file indices
            if not file_choice.isdigit():
                print("invalid input.")
                continue
            
            # set index to the integer value of file_choice minus 1 to account for 0-based indexing of the files list
            index = int(file_choice) - 1

            # Check if the entered index is valid when compared to the length of the files list. If it is valid, call read_plan with the selected file.
            if 0 <= index  and index < len(files):
                read_plan(files[index])
            else:
                print("Invalid selection.")
        
        elif choice == "3":
            files = [file for file in os.listdir(PLANS_DIR_JSON) if file.endswith(".json")] # List only JSON files in the test_cases_json directory

            if not files:
                print("No saved test cases found.")
                continue

            print("\nSaved Test Case Files:")
            for i, file in enumerate(files, start=1):
                print(f"{i}. {file}")
            
            file_choice = input("\nEnter number to run: ")

            if not file_choice.isdigit():
                print("Invalid input.")
                continue

            index = int(file_choice) - 1

            if 0 <= index and index < len(files):
                filepath = os.path.join(PLANS_DIR_JSON, files[index])
                test_cases = load_test_cases(filepath)
                results = execute_tests(test_cases)
                generate_report(results)
            else:
                print("Invalid selection.")

        elif choice == "4":
            print("Goodbye")
            break
        
        else:
            print("Invalid choice, try again.")
