import os
import json
from datetime import datetime
from framework.data.user_generator import create_positive_test_user, create_negative_test_user
from config.config import PLANS_DIR, PLANS_DIR_JSON


def resolve_credentials(case):
    if case["type"] == "positive":
        return create_positive_test_user()
    elif case["type"] == "negative": 
        return create_negative_test_user()
    elif case["type"] == "edge":
        return {
            "username": "",
            "password": ""
        }
    else:
        return {
            "username": "",
            "password": ""
        }

# Load list of test files
def load_test_cases(filepath: str):
    with open(filepath, "r") as file:
        data = json.load(file)
        return data["test_cases"]
    

# Search for test plan files
def list_plans():
    # files returns a list of all files in the test_plans directory that start with "plan_"
    files = [f for f in os.listdir(PLANS_DIR) if f.startswith("plan_")]
    
    # if not files checks if the list is empty. If it is empty, it prints "No test plans found." and returns an empty list. This is to handle the case where there are no plans saved yet.
    if not files:
        print("No test plans found.")
        return[]
    
    print("\nSaved test plans:")

    # enumerate(files, start=1) gives us both the index (starting from 1) and the filename for each file in the list. We can then print them in a numbered list format.
    for i, file in enumerate(files, start=1):
        print(f"{i}. {file}")
    
    return files

# Read test plan file
def read_plan(filename: str):
    filepath = PLANS_DIR / filename
    try:
        with open(filepath, "r") as file:
            content = file.read()
            print("\n--- Plan Content ---\n")
            print(content)
    except FileNotFoundError:
        print(f"File {filename} not found.")

    input("\nPress Enter to continue...")


# Save test cases
def save_test_cases(task: str, test_cases: list):
    safe_task = "".join(
        c for c in task.lower()
        if c.isalnum() or c == " "
    ).strip().replace(" ", "_")[:50]

    txt_path = PLANS_DIR / f"plan_{safe_task}.txt"
    json_path = PLANS_DIR_JSON / f"{safe_task}.json"

    # Write TXT
    with open(txt_path, "w") as file:
        file.write(f"\n=== {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} ===\n")
        file.write("Generated by AI QA Assistant\n")
        file.write(f"Task: {task}\n")
        file.write("\n\n=== Test Cases ===\n")

        for case in test_cases:
            file.write(f"\nTest Case ({case['type']}): {case['title']}\n")
            for i, step in enumerate(case["steps"], start=1):
                file.write(f"{i}. {step}\n")
            file.write(f"Expected: {case['expected']}\n")
            file.write(f"Assertion: {case['assertion']}\n")

    # Write JSON
    with open(json_path, "w") as jf:
        json.dump({"test_cases": test_cases}, jf, indent=4) 