name: Run QA Tests

on:
    push:
        branches: [CICD-Creation]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            
            - name: Install dependencies
              run: |
                pip install playwright python-dotenv
                playwright install
            
            - name: Run tests
              run: |
                python main.py